# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state20230204014116915100000001"
    encrypt = true
    key     = "atlantis/terraform.tfstate"
    region  = "us-east-1"
  }
}
